---
:mailboxes:
  -
    :email: "kartikbehl99@gmail.com"
    :password: "ozsxbwvyjaoruuxv"
    :name: "inbox"
    :delivery_method: postback
    :content_type: text/html
    :delivery_options:
      :delivery_url: "http://localhost:3000/inbox"
      :delivery_username: actionmailbox
      :delivery_password: 12345678